x-base-config: &base-config
  build:
    dockerfile: Dockerfile
    target: genesis-image
    context: .
  user: ${USERID:-1000}:${GROUPID:-1000}
  volumes:
    - ${PWD}:${PWD}
  working_dir: ${PWD}

services:
  build-env:
    <<: *base-config
    environment:
      BUILD_DIR: ${BUILD_DIR:-./build}/docker
      CMAKE_OPTIONS: ${CMAKE_OPTIONS:-}
    command: bash -c "make -j$(nproc)"

  runtime-env:
    <<: *base-config
    environment:
      BUILD_DIR: ${BUILD_DIR:-./build}/docker
    command: bash -c "tail -f /dev/null"
