set(IS_GNU_COMPILER $<CXX_COMPILER_ID:GNU>)
set(IS_CLANG_COMPILER $<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>)
set(IS_UNIX_COMPILER $<OR:${IS_GNU_COMPILER},${IS_CLANG_COMPILER}>)
set(IS_800_VERSION $<VERSION_GREATER_EQUAL:$<CXX_COMPILER_VERSION>,8.0.0>)

list(APPEND GE_UNIX_FLAGS -Werror -Wall -Wextra -Wpedantic)

set(GE_UNIX_COMPILE_OPTIONS $<${IS_UNIX_COMPILER}:${GE_UNIX_FLAGS}>)
list(APPEND GE_COMPILE_OPTIONS
    ${GE_UNIX_COMPILE_OPTIONS})
